server:
  port: 8080


# database 연동 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/userinfo
    username: root
    password: zxcv1234

jpa:
  open-in-view: false
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: auto


